# Generated by Django 6.0.5 on 2026-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(max_length=255)),
                ('summary_en', models.TextField()),
                ('summary_bn', models.TextField()),
                ('content_en', models.TextField(blank=True, default='')),
                ('content_bn', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF Document')], max_length=20)),
                ('media_url', models.URLField(blank=True, default='')),
                ('duration_minutes', models.IntegerField(default=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
