# Generated by Django 6.0.5 on 2026-07-28 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_course_progress', models.IntegerField(default=43)),
                ('sessions_attended', models.IntegerField(default=5)),
                ('tasks_completed', models.IntegerField(default=1)),
                ('total_tasks', models.IntegerField(default=7)),
                ('points_earned', models.IntegerField(default=450)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_metric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress Metric',
                'verbose_name_plural': 'User Progress Metrics',
            },
        ),
    ]
