import 'package:flutter/foundation.dart';
import '../../data/models/category_model.dart';
import '../../data/models/course_model.dart';
import '../../data/models/specialist_model.dart';
import '../../data/models/community_model.dart';

class ApiService {
  List<CategoryModel> getMockCategories() {
    return [
      CategoryModel(
        id: 1,
        slug: 'postpartum-depression',
        titleEn: 'Postpartum Depression',
        titleBn: 'পোস্টপার্টাম ডিপ্রেশন',
        descriptionEn: 'Support and management for postpartum depression and anxiety',
        descriptionBn: 'প্রসূতি পরবর্তী ডিপ্রেশন ও মানসিক বিষণ্নতা দূর করার গাইডলাইন',
        icon: 'mother',
        colorHex: '#EC4899',
      ),
      CategoryModel(
        id: 2,
        slug: 'single-parent',
        titleEn: 'Single Parent',
        titleBn: 'একক অভিভাবক',
        descriptionEn: 'Resources and guidance for single parents',
        descriptionBn: 'একক অভিভাবকদের সন্তানের লালন-পালন ও মানসিক সুস্থতা',
        icon: 'heart',
        colorHex: '#8B5CF6',
      ),
      CategoryModel(
        id: 3,
        slug: 'special-child',
        titleEn: 'Parent of Special Child',
        titleBn: 'বিশেষ চাহিদাসম্পন্ন শিশুর অভিভাবক',
        descriptionEn: 'Specialized support for parents of children with special needs',
        descriptionBn: 'বিশেষ চাহিদাসম্পন্ন শিশুদের অভিভাবকদের জন্য বিশেষ পরামর্শ',
        icon: 'people',
        colorHex: '#3B82F6',
      ),
      CategoryModel(
        id: 4,
        slug: 'corporate-employee',
        titleEn: 'Corporate Employee',
        titleBn: 'কর্পোরেট চাকুরিজীবী',
        descriptionEn: 'Mental wellness support for working professionals',
        descriptionBn: 'কর্মজীবীদের কাজের মানসিক চাপ ও কর্মক্ষেত্রের ভারসাম্যের জন্য সহায়তা',
        icon: 'briefcase',
        colorHex: '#F97316',
      ),
      CategoryModel(
        id: 5,
        slug: 'university-student',
        titleEn: 'University Student',
        titleBn: 'বিশ্ববিদ্যালয় শিক্ষার্থী',
        descriptionEn: 'Stress, anxiety & academic pressure support for students',
        descriptionBn: 'শিক্ষার্থীদের পড়াশোনার চাপ, উদ্বেগ এবং ক্যরিয়ার বিষয়ক মানসিক গাইডলাইন',
        icon: 'school',
        colorHex: '#14B8A6',
      ),
    ];
  }

  List<CourseModel> getMockCourses() {
    return [
      CourseModel(
        id: 1,
        titleEn: 'Postpartum Depression Recovery Program',
        titleBn: 'পোস্টপার্টাম ডিপ্রেশন রিকভারি প্রোগ্রাম',
        subtitleEn: 'Comprehensive 6-week guided recovery for new mothers',
        subtitleBn: 'নতুন মায়েদের প্রসূতি পরবর্তী বিষণ্নতা দূরীকরণে ৬ সপ্তাহের পূর্ণাঙ্গ সহায়িকা',
        categorySlug: 'postpartum-depression',
        thumbnail: 'assets/images/courses_browse_icon.jpg',
        introVideo: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525213/Postpartum_Depression_mood_disorder_after_child_birth_in_Bangla_Dr_Mekhala_Sarkar_-_Dr._Mekhala_Sarkar_720p_h264_twt9ei.mp4',
        instructorName: 'Dr. Fatima Rahman',
        instructorDesignation: 'Senior Maternal Mental Health Specialist',
        instructorPhoto: 'https://corecdn.doctime.com.bd/persons/11799872/profile_photos/dbdgNP0694EIZiZn6oXONLB59vDvgsXFNyVYikD7.png',
        instructorExperience: '10+ Years',
        instructorRating: 4.9,
        specialistName: 'Dr. Ayesha Sultana',
        specialistDegree: 'FCPS (Psychiatry), MS (Clinical Psychology)',
        specialistPhoto: 'https://corecdn.doctime.com.bd/persons/578875/profile_photos/Fe6ibomQLhBJuUQFq4cjQGkAnPeWDtUsO8AOMqIn.png',
        duration: '6 Weeks',
        studentsCount: '2480+',
        rating: 4.9,
        difficulty: 'Beginner',
        price: 0.0,
        isFree: true,
        descriptionEn: 'The Postpartum Depression Recovery Program is designed specifically for new mothers experiencing emotional distress, anxiety, fatigue, and depression after childbirth. Led by experts in maternal mental health, this course guides you step-by-step toward emotional strength and well-being.',
        descriptionBn: 'পোস্টপার্টাম ডিপ্রেশন রিকভারি প্রোগ্রামটি বিশেষভাবে তৈরি করা হয়েছে প্রসূতি পরবর্তী সময়ে বিষণ্নতা, উদ্বেগ, মানসিক ক্লান্তি ও মানসিক চাপে ভোগা মায়েদের জন্য। বিশেষজ্ঞ চিকিৎসকদের তত্ত্বাবধানে পরিচালিত এই কোর্সটি আপনাকে ধীরে ধীরে আবেগীয় শক্তি অর্জন ও সুস্থতায় ফিরিয়ে আনবে।',
        learningOutcomesEn: [
          'Understand postpartum depression vs. baby blues',
          'Develop effective emotional coping strategies for anxiety and guilt',
          'Establish a healthy sleep and nutrition routine post-childbirth',
          'Communicate needs clearly to your partner and family',
          'Strengthen mother-baby bonding through practical daily activities',
          'Build a personal long-term wellness roadmap',
        ],
        learningOutcomesBn: [
          'পোস্টপার্টাম ডিপ্রেশন ও সাধারণ বেবি ব্লুজ এর পার্থক্য বুঝবেন',
          'উদ্বেগ ও অপরাধবোধ কমানোর মানসিক কৌশল শিখবেন',
          'সন্তান জন্মদানের পর সঠিক ঘুম ও নিউট্রিশন রুটিন গঠন করবেন',
          'সঙ্গী ও পরিবারের কাছে নিজের মানসিক চাহিদার কথা প্রকাশ করবেন',
          'সন্তানের সাথে আত্মিক সম্পর্ক ও বন্ডিং সুদৃঢ় করবেন',
          'নিজের জন্য দীর্ঘমেয়াদী মানসিকভাবে সুস্থ থাকার প্ল্যান তৈরি করবেন',
        ],
        modules: [
          CourseModule(
            id: 'm1',
            title: 'Module 1 – Understanding Postpartum Depression',
            description: 'Learn the fundamentals of postpartum mood disorders.',
            lessons: [
              CourseLesson(
                id: 'l1',
                title: 'Lesson 1: Introduction to Postpartum Depression',
                duration: '18 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525213/Postpartum_Depression_mood_disorder_after_child_birth_in_Bangla_Dr_Mekhala_Sarkar_-_Dr._Mekhala_Sarkar_720p_h264_twt9ei.mp4',
                description: 'Overview of postpartum depression symptoms and emotional changes after childbirth.',
              ),
              CourseLesson(
                id: 'l2',
                title: 'Lesson 2: Baby Blues vs Postpartum Depression',
                duration: '11 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525764/Baby_Blues_vs_Postpartum_Depression_Which_is_it_-_The_Maternity_Mentor_360p_h264_pmxptj.mp4',
                description: 'Differentiating temporary baby blues from clinical postpartum depression.',
              ),
              CourseLesson(
                id: 'l3',
                title: 'Lesson 3: Common Symptoms & Warning Signs',
                duration: '10 mins',
                type: 'pdf',
                contentUrl: 'https://www.docs.sasg.ed.ac.uk/StudentCounselling/SCSbooklets/SCSstressbooklet.pdf',
                description: 'PDF guide listing physical, emotional, and behavioral warning signs.',
              ),
            ],
          ),
          CourseModule(
            id: 'm2',
            title: 'Module 2 – Emotional Recovery',
            description: 'Techniques for managing anxiety, fear, and mom guilt.',
            lessons: [
              CourseLesson(
                id: 'l4',
                title: 'Lesson 4: Managing Anxiety & Fear',
                duration: '20 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525679/Anxiety_Disorder_what_s_an_anxiety_disorder_anxiety_symptoms_treatment_in_bangla_-_Health_Inside_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_720p_h264_kkvvdp.mp4',
                description: 'Understanding postpartum anxiety disorders and treatment strategies.',
              ),
              CourseLesson(
                id: 'l5',
                title: 'Lesson 5: Coping with Guilt',
                duration: '12 mins',
                type: 'audio',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785524287/A_Guided_Meditation_for_Releasing_Guilt_-_Great_Meditation_hku8ku.mp3',
                description: 'Guided audio meditation to overcome guilt and self-blame as a new mother.',
              ),
              CourseLesson(
                id: 'l6',
                title: 'Lesson 6: Building Emotional Strength',
                duration: '14 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
                description: 'Key principles for developing mental resilience during maternal transition.',
              ),
            ],
          ),
          CourseModule(
            id: 'm3',
            title: 'Module 3 – Self Care & Health',
            description: 'Restorative practices for sleep, diet, and relaxation.',
            lessons: [
              CourseLesson(
                id: 'l7',
                title: 'Lesson 7: Healthy Sleep Routine',
                duration: '15 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785524459/TOP_10_Tips_for_Better_Sleep_For_Parents_With_A_Newborn_Baby_-_Bridget_Teyler_720p_h264_dnwur7.mp4',
                description: 'Top tips for maximizing sleep quality with a newborn baby.',
              ),
              CourseLesson(
                id: 'l8',
                title: 'Lesson 8: Nutrition After Childbirth',
                duration: '12 mins',
                type: 'pdf',
                contentUrl: 'https://www.globalfamilydoctor.com/site/DefaultSite/filesystem/documents/resources/MHGuidebook-EBookDownload.pdf',
                description: 'Nutritional guide for postpartum physical and mental recovery.',
              ),
              CourseLesson(
                id: 'l9',
                title: 'Lesson 9: Relaxation Meditation',
                duration: '16 mins',
                type: 'audio',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526845/%E0%A6%AE%E0%A7%87%E0%A6%A1%E0%A6%BF%E0%A6%9F%E0%A7%87%E0%A6%B6%E0%A6%A8_%E0%A6%B6%E0%A6%BF%E0%A6%A5%E0%A6%BF%E0%A6%B2%E0%A6%BE%E0%A6%AF%E0%A6%BC%E0%A6%A8_%E0%A6%86%E0%A6%B0%E0%A6%BE%E0%A6%AE_%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%95%E0%A7%8D%E0%A6%B0%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A6%BE_Meditation_Relaxation_-_Quantum_Meditation_for_All_k5ee2j.mp3',
                description: 'Bangla quantum relaxation meditation audio for stress reduction.',
              ),
            ],
          ),
          CourseModule(
            id: 'm4',
            title: 'Module 4 – Family & Social Support',
            description: 'Communicating with partners and building support systems.',
            lessons: [
              CourseLesson(
                id: 'l10',
                title: 'Lesson 10: Communicating with Your Partner',
                duration: '18 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526901/Dr._Catherine_Monk_Key_Relationships_During_Pregnancy_-_Simms_Mann_Institute_720p_h264_zttynb.mp4',
                description: 'Maintaining healthy communication and marital relationships during postpartum.',
              ),
              CourseLesson(
                id: 'l11',
                title: 'Lesson 11: Accepting Help Without Guilt',
                duration: '9 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785524298/Accepting_Help_Without_the_Guilt_-_Definition_Discovery_720p_h264_ejepyy.mp4',
                description: 'Learning to delegate tasks and accept support gracefully.',
              ),
              CourseLesson(
                id: 'l12',
                title: 'Lesson 12: Creating a Support Network',
                duration: '15 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526901/Dr._Catherine_Monk_Key_Relationships_During_Pregnancy_-_Simms_Mann_Institute_720p_h264_zttynb.mp4',
                description: 'Connecting with family, peers, and mothers groups.',
              ),
            ],
          ),
          CourseModule(
            id: 'm5',
            title: 'Module 5 – Baby Bonding',
            description: 'Fostering a deep bond with your child.',
            lessons: [
              CourseLesson(
                id: 'l13',
                title: 'Lesson 13: Bonding Activities',
                duration: '12 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525764/Baby_Blues_vs_Postpartum_Depression_Which_is_it_-_The_Maternity_Mentor_360p_h264_pmxptj.mp4',
                description: 'Interactive play, eye contact, and emotional connection exercises.',
              ),
              CourseLesson(
                id: 'l14',
                title: 'Lesson 14: Skin-to-Skin Care',
                duration: '10 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785524459/TOP_10_Tips_for_Better_Sleep_For_Parents_With_A_Newborn_Baby_-_Bridget_Teyler_720p_h264_dnwur7.mp4',
                description: 'Benefits and techniques of skin-to-skin touch for maternal bonding.',
              ),
            ],
          ),
          CourseModule(
            id: 'm6',
            title: 'Module 6 – Recovery Plan',
            description: 'Long-term wellness planning and professional escalation.',
            lessons: [
              CourseLesson(
                id: 'l15',
                title: 'Lesson 15: Weekly Wellness Planning',
                duration: '14 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
                description: 'Setting realistic weekly goals for self-care and mental health.',
              ),
              CourseLesson(
                id: 'l16',
                title: 'Lesson 16: When to Contact a Professional',
                duration: '15 mins',
                type: 'audio',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785524563/%E0%A6%95%E0%A6%96%E0%A6%A8_%E0%A6%AE%E0%A6%A8%E0%A7%8B%E0%A6%B0%E0%A7%8B%E0%A6%97_%E0%A6%AC%E0%A6%BF%E0%A6%B6%E0%A7%87%E0%A6%B7%E0%A6%9C%E0%A7%8D%E0%A6%9E_%E0%A6%A6%E0%A7%87%E0%A6%96%E0%A6%AB%E0%A7%87%E0%A6%A8_Kokhon_Psychiatrist_Dekhaben_Mental_Health_Bangla_-_Health_Care_Bangla_l0wsk3.mp3',
                description: 'Identifying when clinical intervention or therapy is needed.',
              ),
              CourseLesson(
                id: 'l17',
                title: 'Lesson 17: Recovery Roadmap',
                duration: '10 mins',
                type: 'pdf',
                contentUrl: 'https://crpf.gov.in/writereaddata/images/pdf/Think_Straight.pdf',
                description: 'Downloadable roadmap for sustained mental resilience.',
              ),
            ],
          ),
        ],
        assignments: [
          CourseAssignment(
            id: 'a1',
            title: 'Assignment 1: 7-Day Mood Journal',
            description: 'Track your emotions, sleep, meals, and thoughts every day for 7 days.',
            type: 'mood_journal',
          ),
          CourseAssignment(
            id: 'a2',
            title: 'Assignment 2: Sleep Tracker',
            description: 'Log bedtime, wake time, total hours, and sleep quality rating for one week.',
            type: 'sleep_tracker',
          ),
          CourseAssignment(
            id: 'a3',
            title: 'Assignment 3: Daily Gratitude Journal',
            description: 'Record 3 positive items daily and write a 50-word reflection.',
            type: 'gratitude_journal',
          ),
          CourseAssignment(
            id: 'a4',
            title: 'Assignment 4: Self-Care Checklist',
            description: 'Check off daily healthy habits (water, walking, breathing, resting).',
            type: 'self_care_checklist',
          ),
          CourseAssignment(
            id: 'a5',
            title: 'Assignment 5: Mother–Baby Bonding Activity',
            description: 'Perform skin-to-skin, eye contact, and singing activities, and submit reflection.',
            type: 'bonding_activity',
          ),
          CourseAssignment(
            id: 'a6',
            title: 'Final Assignment: 300-Word Recovery Reflection',
            description: 'Write a 300-word reflection covering your recovery journey to unlock your completion certificate.',
            type: 'final_reflection',
          ),
        ],
        quizQuestions: [
          QuizQuestion(
            id: 1,
            question: 'What is a primary distinction between Baby Blues and Postpartum Depression?',
            options: [
              'Baby blues resolves within 2 weeks; PPD lasts longer and is more severe.',
              'Baby blues requires hospitalization, PPD does not.',
              'PPD only occurs before childbirth.',
              'Baby blues has no emotional symptoms.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 2,
            question: 'Which of the following is a common physical symptom of postpartum depression?',
            options: [
              'Extreme fatigue and insomnia',
              'Heightened energy levels',
              'Sudden improvement in vision',
              'No physical symptoms occur'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 3,
            question: 'How does skin-to-skin contact benefit a newborn and mother?',
            options: [
              'It releases oxytocin, reduces stress, and strengthens emotional bonding.',
              'It accelerates hair growth.',
              'It replaces proper newborn nutrition.',
              'It increases blood pressure.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 4,
            question: 'What is the recommended approach when feeling overwhelmed by guilt as a new mother?',
            options: [
              'Acknowledge feelings without self-judgment and practice self-compassion.',
              'Isolate yourself from all family members.',
              'Ignore your feelings completely.',
              'Stop eating meals.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 5,
            question: 'When should a new mother seek immediate professional help from a psychiatrist or doctor?',
            options: [
              'When experiencing persistent thoughts of self-harm or inability to care for baby.',
              'Only after 1 year has passed.',
              'Never; self-care is always sufficient.',
              'Only when recommended by neighbors.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 6,
            question: 'Which daily activity significantly aids postpartum emotional recovery?',
            options: [
              'Gentle walking, fresh air, and deep breathing exercises.',
              'Staying awake for 48 hours continuously.',
              'Avoiding all communication with partner.',
              'Skipping meals regularly.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 7,
            question: 'What role does partner communication play in postpartum recovery?',
            options: [
              'Openly expressing needs reduces anxiety and shares caregiving responsibilities.',
              'Partner communication increases postpartum stress.',
              'Partners should not be involved in newborn care.',
              'It has no effect on emotional health.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 8,
            question: 'What is the target passing score for the Ashwash course quiz?',
            options: ['70%', '50%', '90%', '100%'],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 9,
            question: 'How does daily gratitude writing impact mental state?',
            options: [
              'Shifts focus toward positive aspects and reduces stress hormones.',
              'Increases sadness.',
              'Has no psychological effect.',
              'Causes sleep deprivation.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 10,
            question: 'Which hormone promotes bonding during breastfeeding and cuddling?',
            options: ['Oxytocin', 'Adrenaline', 'Cortisol', 'Insulin'],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 11,
            question: 'What should you do if you cannot sleep even when your baby is sleeping?',
            options: [
              'Practice body scan relaxation meditation and consult a professional if persistent.',
              'Watch intense action movies.',
              'Drink heavy caffeinated drinks.',
              'Worry continuously.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 12,
            question: 'Is postpartum depression a personal failure or weakness?',
            options: [
              'No, it is a medical condition caused by hormonal shifts and psychological stress.',
              'Yes, it is caused by weak willpower.',
              'Yes, it means you do not love your baby.',
              'None of the above.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 13,
            question: 'What is an effective way for family members to support a mother with PPD?',
            options: [
              'Help with household chores, meal prep, and infant care without judgment.',
              'Tell her to snap out of it.',
              'Leave her completely alone.',
              'Critique her parenting skills.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 14,
            question: 'What is the purpose of keeping a daily mood journal?',
            options: [
              'To track emotional triggers and observe recovery progress over time.',
              'To criticize past actions.',
              'To replace doctor visits entirely.',
              'To fulfill a legal requirement.'
            ],
            correctAnswerIndex: 0,
          ),
          QuizQuestion(
            id: 15,
            question: 'What happens once all lessons, assignments, and the quiz are completed?',
            options: [
              'An official downloadable Ashwash Recovery Certificate is unlocked!',
              'The course locks permanently.',
              'You must pay a fee.',
              'All data is deleted.'
            ],
            correctAnswerIndex: 0,
          ),
        ],
        certificateAvailable: true,
        relatedCourseIds: [2, 3, 4],
      ),
      CourseModel(
        id: 2,
        titleEn: 'Single Parent Resilience & Child Care',
        titleBn: 'একক অভিভাবকের মানসিক শক্তি ও সন্তান লালন-পালন',
        subtitleEn: 'Balancing responsibilities and emotional strength',
        subtitleBn: 'দায়িত্বশীল লালন-পালন ও মানসিক প্রশান্তি',
        categorySlug: 'single-parent',
        thumbnail: 'assets/images/courses_browse_icon.jpg',
        introVideo: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
        instructorName: 'Nazmun Nahar Munmun',
        instructorDesignation: 'Clinical Psychologist',
        instructorPhoto: 'https://corecdn.doctime.com.bd/persons/578875/profile_photos/Fe6ibomQLhBJuUQFq4cjQGkAnPeWDtUsO8AOMqIn.png',
        instructorExperience: '9+ Years',
        instructorRating: 5.0,
        specialistName: 'Jahanur Akter',
        specialistDegree: 'BSc & MSc (Psychology)',
        specialistPhoto: 'https://corecdn.doctime.com.bd/persons/11799872/profile_photos/dbdgNP0694EIZiZn6oXONLB59vDvgsXFNyVYikD7.png',
        duration: '4 Weeks',
        studentsCount: '1520+',
        rating: 4.8,
        difficulty: 'Intermediate',
        price: 0.0,
        isFree: true,
        descriptionEn: 'Support and mental health strategies tailored for single mothers and fathers managing single parenthood.',
        descriptionBn: 'একক বাবা ও মায়েদের সন্তান লালন-পালন ও কাজের মাঝে মানসিক চাপ সামলানোর বৈজ্ঞানিক কোর্স।',
        learningOutcomesEn: [
          'Manage parental stress and burnout',
          'Set healthy emotional boundaries',
          'Communicate effectively with children',
        ],
        learningOutcomesBn: [
          'অভিভাবকত্বের মানসিক চাপ নিয়ন্ত্রণ',
          'সন্তানের সাথে ইতিবাচক সম্পর্ক বজায় রাখা',
        ],
        modules: [
          CourseModule(
            id: 'sp_m1',
            title: 'Module 1 – Single Parent Mental Strength',
            lessons: [
              CourseLesson(
                id: 'sp_l1',
                title: 'Lesson 1: Overcoming Parental Stress',
                duration: '15 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
              ),
            ],
          ),
        ],
        assignments: [
          CourseAssignment(
            id: 'sp_a1',
            title: 'Daily Self-Care Checklist',
            description: 'Log 3 daily single parent self-care tasks.',
            type: 'self_care_checklist',
          ),
        ],
        quizQuestions: [
          QuizQuestion(
            id: 1,
            question: 'What is a healthy way to manage single parent stress?',
            options: ['Setting clear routines and asking for help', 'Working non-stop', 'Ignoring emotions', 'Isolating'],
            correctAnswerIndex: 0,
          ),
        ],
        certificateAvailable: true,
        relatedCourseIds: [1, 3],
      ),
      CourseModel(
        id: 3,
        titleEn: 'Special Child Parenting & Mindfulness',
        titleBn: 'বিশেষ চাহিদা সম্পন্ন শিশুর অভিভাবকত্ব কোর্স',
        subtitleEn: 'Empathy, patience, and specialized care',
        subtitleBn: 'ধৈর্য ও মমতায় শিশু লালন-পালন',
        categorySlug: 'special-child',
        thumbnail: 'assets/images/courses_browse_icon.jpg',
        introVideo: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525679/Anxiety_Disorder_what_s_an_anxiety_disorder_anxiety_symptoms_treatment_in_bangla_-_Health_Inside_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_720p_h264_kkvvdp.mp4',
        instructorName: 'Ashraful Alam Khan',
        instructorDesignation: 'Special Educator & Therapist',
        instructorPhoto: 'https://corecdn.doctime.com.bd/persons/579701/profile_photos/VdlPFID5h5sqcb77vNNAgCfMQRYhOWIvPAhf8iaf.png',
        instructorExperience: '17+ Years',
        instructorRating: 4.9,
        specialistName: 'Ambia Khatun',
        specialistDegree: 'MPhil (Psychology)',
        specialistPhoto: 'https://corecdn.doctime.com.bd/persons/10144935/profile_photos/fdL2DM8mPNXERcFmFeT0rh6LuxeHsavaxPf1INkE.png',
        duration: '5 Weeks',
        studentsCount: '980+',
        rating: 4.9,
        difficulty: 'Intermediate',
        price: 0.0,
        isFree: true,
        descriptionEn: 'Guidance and therapeutic tools for parents of children with neurodivergent or special needs.',
        descriptionBn: 'বিশেষ চাহিদাসম্পন্ন শিশুদের অভিভাবকদের জন্য প্রাকটিক্যাল সাপোর্ট ও মাইন্ডফুলনেস।',
        learningOutcomesEn: ['Sensory integration techniques', 'Patience & parental mindfulness'],
        learningOutcomesBn: ['শিশুর সাথে যোগাযোগ বাড়ানো', 'অভিভাবকের মানসিক শান্তি'],
        modules: [
          CourseModule(
            id: 'sc_m1',
            title: 'Module 1 – Understanding Special Needs',
            lessons: [
              CourseLesson(
                id: 'sc_l1',
                title: 'Lesson 1: Sensory Integration Tips',
                duration: '14 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525679/Anxiety_Disorder_what_s_an_anxiety_disorder_anxiety_symptoms_treatment_in_bangla_-_Health_Inside_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_720p_h264_kkvvdp.mp4',
              ),
            ],
          ),
        ],
        assignments: [],
        quizQuestions: [],
        certificateAvailable: true,
        relatedCourseIds: [1, 2],
      ),
      CourseModel(
        id: 4,
        titleEn: 'Corporate Burnout & Stress Mastery',
        titleBn: 'কর্পোরেট বার্নআউট ও স্ট্রেস সামলানোর গাইড',
        subtitleEn: 'Work-life balance and anxiety relief',
        subtitleBn: 'কাজের চাপ ও বিষণ্নতা নিয়ন্ত্রণ',
        categorySlug: 'corporate-employee',
        thumbnail: 'assets/images/courses_browse_icon.jpg',
        introVideo: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
        instructorName: 'Md. Wahid Anowar',
        instructorDesignation: 'Corporate Mental Health Consultant',
        instructorPhoto: 'https://corecdn.doctime.com.bd/persons/664527/profile_photos/99U345LD5IrdJi1i1lRTLAUJ0zARFVNspcHLHgYh.jpg',
        instructorExperience: '3+ Years',
        instructorRating: 4.8,
        specialistName: 'Nazmun Nahar Munmun',
        specialistDegree: 'MS (Clinical Psychology)',
        specialistPhoto: 'https://corecdn.doctime.com.bd/persons/578875/profile_photos/Fe6ibomQLhBJuUQFq4cjQGkAnPeWDtUsO8AOMqIn.png',
        duration: '3 Weeks',
        studentsCount: '3100+',
        rating: 4.8,
        difficulty: 'Beginner',
        price: 0.0,
        isFree: true,
        descriptionEn: 'Practical strategies to prevent burnout, manage workplace anxiety, and optimize performance.',
        descriptionBn: 'কর্মক্ষেত্রে উচ্চ মানসিক চাপ, উদ্বেগ ও বার্নআউট মুক্ত থাকার কৌশল।',
        learningOutcomesEn: ['Workplace boundaries', 'Stress relief techniques'],
        learningOutcomesBn: ['কর্মক্ষেত্রের চাপ সামলানো'],
        modules: [
          CourseModule(
            id: 'corp_m1',
            title: 'Module 1 – Stress Physiology',
            lessons: [
              CourseLesson(
                id: 'corp_l1',
                title: 'Lesson 1: Defeating Workplace Burnout',
                duration: '16 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785526641/7_Secrets_To_Becoming_Mentally_Tougher_-_Psych2Go_720p_h264_tftysh.mp4',
              ),
            ],
          ),
        ],
        assignments: [],
        quizQuestions: [],
        certificateAvailable: true,
        relatedCourseIds: [1, 5],
      ),
      CourseModel(
        id: 5,
        titleEn: 'Student Exam Anxiety & Focus Boost',
        titleBn: 'পরীক্ষার ভয় ও পড়ার মনোযোগ বাড়ানোর উপায়',
        subtitleEn: 'Academic pressure & concentration mastery',
        subtitleBn: 'মনোযোগ ও মানসিক প্রশান্তি',
        categorySlug: 'university-student',
        thumbnail: 'assets/images/courses_browse_icon.jpg',
        introVideo: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525679/Anxiety_Disorder_what_s_an_anxiety_disorder_anxiety_symptoms_treatment_in_bangla_-_Health_Inside_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_720p_h264_kkvvdp.mp4',
        instructorName: 'Ambia Khatun',
        instructorDesignation: 'Educational Psychologist',
        instructorPhoto: 'https://corecdn.doctime.com.bd/persons/10144935/profile_photos/fdL2DM8mPNXERcFmFeT0rh6LuxeHsavaxPf1INkE.png',
        instructorExperience: '4+ Years',
        instructorRating: 5.0,
        specialistName: 'Jahanur Akter',
        specialistDegree: 'MSc (Psychology)',
        specialistPhoto: 'https://corecdn.doctime.com.bd/persons/11799872/profile_photos/dbdgNP0694EIZiZn6oXONLB59vDvgsXFNyVYikD7.png',
        duration: '3 Weeks',
        studentsCount: '4200+',
        rating: 4.9,
        difficulty: 'Beginner',
        price: 0.0,
        isFree: true,
        descriptionEn: 'Helps university students overcome exam fear, study paralysis, and maintain focus.',
        descriptionBn: 'বিশ্ববিদ্যালয় শিক্ষার্থীদের পড়াশোনার চাপ, উদ্বেগ এবং ক্যারিয়ার বিষন্নতা কাটানোর উপায়।',
        learningOutcomesEn: ['Exam anxiety relief', 'Focus & memory techniques'],
        learningOutcomesBn: ['মনোযোগ বৃদ্ধি ও পরীক্ষার ভয় দূরকরণ'],
        modules: [
          CourseModule(
            id: 'st_m1',
            title: 'Module 1 – Overcoming Study Anxiety',
            lessons: [
              CourseLesson(
                id: 'st_l1',
                title: 'Lesson 1: Focus Building Exercises',
                duration: '12 mins',
                type: 'video',
                contentUrl: 'https://res.cloudinary.com/a6cztdgv/video/upload/v1785525679/Anxiety_Disorder_what_s_an_anxiety_disorder_anxiety_symptoms_treatment_in_bangla_-_Health_Inside_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_720p_h264_kkvvdp.mp4',
              ),
            ],
          ),
        ],
        assignments: [],
        quizQuestions: [],
        certificateAvailable: true,
        relatedCourseIds: [1, 4],
      ),
    ];
  }

  List<SpecialistModel> getMockSpecialists() {
    return [
      SpecialistModel(
        id: 10,
        name: 'Jaba Acharjee',
        degree: 'MSc in Clinical Psychology (BSMMU)',
        specialization: 'Postpartum & Maternal Mental Health Specialist',
        workingPlace: 'Ashwash Mental Wellness & BSMMU',
        imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500',
        titleEn: 'Clinical Psychologist',
        titleBn: 'ক্লিনিক্যাল সাইকোলজিস্ট',
        bioEn: 'Jaba Acharjee is a senior mental health specialist on Ashwash.',
        bioBn: 'জবা আচার্য্য আশ্বাস প্ল্যাটফর্মের একজন সিনিয়র মানসিক স্বাস্থ্য বিশেষজ্ঞ।',
        experienceYears: 8,
        rating: 5.0,
        feeBdt: 1200,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 1,
        name: 'Jahanur Akter',
        degree: 'BSc (Psychology), MSc (Psychology)',
        specialization: 'Psychology & Mental Health Counseling',
        workingPlace: 'Healthx',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/11799872/profile_photos/dbdgNP0694EIZiZn6oXONLB59vDvgsXFNyVYikD7.png',
        titleEn: 'BSc (Psychology), MSc (Psychology)',
        titleBn: 'বিএসসি ও এমএসসি (সাইকোলজি)',
        bioEn: 'Experienced Counseling Psychologist at Healthx with 5+ years of clinical counseling experience.',
        bioBn: 'হেলথ-এক্স এর অভিজ্ঞ কাউন্সেলিং সাইকোলজিস্ট (৫+ বছরের অভিজ্ঞতা)।',
        experienceYears: 5,
        rating: 4.9,
        feeBdt: 500,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 2,
        name: 'Nazmun Nahar Munmun',
        degree: 'BSc (Psychology), MS (Clinical Psychology)',
        specialization: 'Clinical Psychology & CBT Therapy',
        workingPlace: 'Dhaka College',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/578875/profile_photos/Fe6ibomQLhBJuUQFq4cjQGkAnPeWDtUsO8AOMqIn.png',
        titleEn: 'BSc (Psychology), MS (Clinical Psychology)',
        titleBn: 'বিএসসি (সাইকোলজি), এমএস (ক্লিনিক্যাল সাইকোলজি)',
        bioEn: 'Senior Clinical Psychologist based at Dhaka College with 9+ years expertise in CBT & stress therapy.',
        bioBn: 'ঢাকা কলেজের সিনিয়র ক্লিনিক্যাল সাইকোলজিস্ট (৯+ বছরের অভিজ্ঞতা)।',
        experienceYears: 9,
        rating: 5.0,
        feeBdt: 600,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 3,
        name: 'Ashraful Alam Khan',
        degree: 'BSc (Psychology), MS (Psychology)',
        specialization: 'Psychology & Audiology Therapy',
        workingPlace: 'Moner Shusthota, Audiology Bangladesh',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/579701/profile_photos/VdlPFID5h5sqcb77vNNAgCfMQRYhOWIvPAhf8iaf.png',
        titleEn: 'BSc (Psychology), MS (Psychology)',
        titleBn: 'বিএসসি (সাইকোলজি), এমএস (সাইকোলজি)',
        bioEn: 'Veteran Psychologist at Moner Shusthota & Audiology Bangladesh with 17+ years of experience.',
        bioBn: 'মনের সুস্থতা ও অডিওলজি বাংলাদেশের প্রবীণ সাইকোলজিস্ট (১৭+ বছরের অভিজ্ঞতা)।',
        experienceYears: 17,
        rating: 4.9,
        feeBdt: 800,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 4,
        name: 'Md. Wahid Anowar',
        degree: 'BSc (Psychology), MS (Psychology)',
        specialization: 'Psychological Consultancy & Youth Therapy',
        workingPlace: 'Restart- Psychological Consultancy',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/664527/profile_photos/99U345LD5IrdJi1i1lRTLAUJ0zARFVNspcHLHgYh.jpg',
        titleEn: 'BSc (Psychology), MS (Psychology)',
        titleBn: 'বিএসসি (সাইকোলজি), এমএস (সাইকোলজি)',
        bioEn: 'Psychological Consultant at Restart- Psychological Consultancy specializing in youth anxiety.',
        bioBn: 'রিস্টার্ট সাইকোলজিক্যাল কনসালটেন্সির অভিজ্ঞ পরামর্শক (৩+ বছরের অভিজ্ঞতা)।',
        experienceYears: 3,
        rating: 4.8,
        feeBdt: 500,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 5,
        name: 'Ambia Khatun',
        degree: 'MPhil (Psychology), MSc (Psychology)',
        specialization: 'Psychology & Educational Counseling',
        workingPlace: 'Bangladesh Open University',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/10144935/profile_photos/fdL2DM8mPNXERcFmFeT0rh6LuxeHsavaxPf1INkE.png',
        titleEn: 'MPhil (Psychology), MSc (Psychology)',
        titleBn: 'এমফিল (সাইকোলজি), এমএসসি (সাইকোলজি)',
        bioEn: 'Educational and Clinical Psychologist at Bangladesh Open University with 4+ years experience.',
        bioBn: 'বাংলাদেশ উন্মুক্ত বিশ্ববিদ্যালয়ের শিক্ষা ও মানসিক স্বাস্থ্য মনোবিজ্ঞানী (৪+ বছরের অভিজ্ঞতা)।',
        experienceYears: 4,
        rating: 5.0,
        feeBdt: 500,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 6,
        name: 'Dr. Sharmin Akter',
        degree: 'FCPS (Psychiatry), MSc (Clinical Psychology)',
        specialization: 'Postpartum & Maternal Mental Health Specialist',
        workingPlace: 'Ashwash Wellness & BSMMU',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/11799872/profile_photos/dbdgNP0694EIZiZn6oXONLB59vDvgsXFNyVYikD7.png',
        titleEn: 'FCPS (Psychiatry)',
        titleBn: 'এফসিপিএস (সাইকিয়াট্রি)',
        bioEn: 'Specialist in postpartum depression, maternal anxiety, and mindfulness meditation.',
        bioBn: 'প্রসূতি পরবর্তী ডিপ্রেশন ও মাইন্ডফুলনেস মেডিটেশন বিশেষজ্ঞ চিকিৎসক।',
        experienceYears: 8,
        rating: 4.9,
        feeBdt: 1200,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 7,
        name: 'Dr. Anisur Rahman',
        degree: 'MD (Psychiatry), MBBS (DMC)',
        specialization: 'Consultant Psychiatrist & Sleep Specialist',
        workingPlace: 'Dhaka Medical College & Hospital',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/664527/profile_photos/99U345LD5IrdJi1i1lRTLAUJ0zARFVNspcHLHgYh.jpg',
        titleEn: 'MD (Psychiatry)',
        titleBn: 'এমডি (সাইকিয়াট্রি)',
        bioEn: 'Expert consultant treating workplace burnout, severe insomnia, and panic disorders.',
        bioBn: 'কর্মক্ষেত্রের বার্নআউট, অনিদ্রা ও প্যানিক ডিসঅর্ডার বিশেষজ্ঞ।',
        experienceYears: 11,
        rating: 4.8,
        feeBdt: 1500,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
      SpecialistModel(
        id: 8,
        name: 'Dr. Farhana Islam',
        degree: 'M.Phil (Clinical Psychology), CBT Certified',
        specialization: 'Child & Adolescent Psychologist',
        workingPlace: 'National Institute of Mental Health (NIMH)',
        imageUrl: 'https://corecdn.doctime.com.bd/persons/578875/profile_photos/Fe6ibomQLhBJuUQFq4cjQGkAnPeWDtUsO8AOMqIn.png',
        titleEn: 'M.Phil (Clinical Psychology)',
        titleBn: 'এমফিল (ক্লিনিক্যাল সাইকোলজি)',
        bioEn: 'Child & adolescent behavioral therapist specializing in neurodivergent care.',
        bioBn: 'শিশু ও কিশোর-কিশোরীদের আবেগীয় সমস্যা ও কগনিটিভ বিহেভিয়ার থেরাপিস্ট।',
        experienceYears: 7,
        rating: 5.0,
        feeBdt: 1000,
        locationType: 'local',
        isAvailable: true,
        isOnline: true,
      ),
    ];
  }

  List<PostModel> getMockPosts() {
    return [
      PostModel(
        id: 1,
        authorAlias: 'Anonymous',
        content: 'I just completed my first week of anxiety management course. Feeling hopeful! 💜',
        tag: 'Success Story',
        isAnonymous: true,
        likesCount: 24,
        commentsCount: 8,
        isLiked: false,
        createdAt: '2 hours ago',
      ),
      PostModel(
        id: 2,
        authorAlias: 'Fatima K.',
        content: 'Any tips for first-time mothers dealing with postpartum anxiety?',
        tag: 'Question',
        isAnonymous: false,
        likesCount: 15,
        commentsCount: 12,
        isLiked: false,
        createdAt: '5 hours ago',
      ),
    ];
  }
}
