# Generated by Django 6.0.7 on 2026-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_bn',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_bn',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selected_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sessions_attended',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='PATIENT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.category'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
