# Generated by Django 6.0.7 on 2026-08-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_title_bn_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('SPECIALIST', 'Psychologist / Specialist'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')], default='PATIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='female', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(default='Clinical Psychologist', max_length=150)),
                ('hospital_clinic', models.CharField(default='Ashwash Mental Wellness Center', max_length=200)),
                ('experience_years', models.IntegerField(default=5)),
                ('qualification', models.CharField(default='MSc in Clinical Psychology, BSMMU', max_length=200)),
                ('medical_license_number', models.CharField(max_length=100)),
                ('medical_license_document', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('languages', models.CharField(default='Bengali, English', max_length=150)),
                ('consultation_fee_bdt', models.IntegerField(default=1500)),
                ('available_days', models.JSONField(default=list)),
                ('available_time_slots', models.JSONField(default=list)),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('total_reviews', models.IntegerField(default=48)),
                ('bio', models.TextField(blank=True, default='Dedicated mental health specialist empowering mothers and individuals to build emotional resilience.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
