# Generated by Django 6.0.5 on 2026-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('meeting_link', models.URLField(default='https://meet.google.com/ash-wash-wellness')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('title_bn', models.CharField(max_length=150)),
                ('bio_en', models.TextField()),
                ('bio_bn', models.TextField()),
                ('experience_years', models.IntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('fee_bdt', models.IntegerField(default=1500)),
                ('location_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
