# Generated by Django 6.0.7 on 2026-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
